### ISSUE TITLE
Broken: Shift Palette Color Index Brush

### ISSUE THREAD

**Issue by gingerbeardman** [gingerbeardman/piskel-playdate#18]
Shift Palette Color Index Brush

- currently it does nothing
- broken

**Comment by ayushmanchhabra** [comment]
At which commit did this break?

Not familiar with this feature - could you tell me how it should work?

**Comment by gingerbeardman** [comment]
It was a tool I added from a PR on the main branch. It's new very recently.

I just checked it again and it is working, it just requires some understanding to set and use.

**Comment by gingerbeardman** [comment]
it's all in the tool description but it took me reading it a couple of times to "get it".

1. have a palette of shades
2. important: set primary and secondary to each end of the range of shades you are working in (not doing so will result in the tool having no effect)
3. drawing with this brush will shift the colours up the scale (and back using cmd)

Pretty cool.


https://github.com/gingerbeardman/piskel-playdate/assets/49612/dde24c91-ac0d-45c0-b299-006023c74908
