### ISSUE TITLE
Exported image is wrong size when imported via drag and drop and exported using hot key

### ISSUE THREAD

**Issue by gingerbeardman** [gingerbeardman/piskel-playdate#8]
Bug description

(this template is intended for bug reports, erase it when requesting features/enhancements)

### Steps to reproduce the bug
1. drag a PNG on Piskel to import
1. accept new size and import
1. edit
1. export using hot key

![image](https://github.com/gingerbeardman/piskel-playdate/assets/49612/b7bc517d-3d91-4a17-8cfe-5a1ac12fc540)

Expected
- export should be current size, that was shown and accepted at import

Actual
- size is unexpected, it is the default piskel canvas size of 300x150

Confirmation
- export using user interface gives expected 99x59 image

### Environment details
* operating system: macOS ARM
* browser (or offline application version): [4e49746](https://github.com/gingerbeardman/piskel-playdate/commit/4e497469bb5f1ed314bb313cf4ddb4c863dbbbac)

### Sprite details
* number of frames: 1
* sprite resolution: 99x59

### Image

![1](https://github.com/gingerbeardman/piskel-playdate/assets/49612/97482914-da30-4ad6-bab5-32e3824a3e77)

**Comment by ayushmanchhabra** [comment]
Found the root cause. The `Selected Frame Export` option should be hooked to the `Ctrl+Shift+E` shortcut. This will export it as a single frame with the correct dimensions.
